### ISSUE TITLE
Add geometry columns CENTER_X_COORDINATE and CENTER_Y_COORDINATE

### ISSUE THREAD

**Issue by jnspitale** [SETI/rms-data-projects#102]
Add to body and ring tables.   uv coordinates of the center of each body/ring in the table whose center appears int he FOV.  

format: 8.2
null constant: -99999999.

**Comment by rfrenchseti** [comment]
This is a duplicate of #93

**Comment by jnspitale** [comment]
Closed, in favor of #93
