### ISSUE TITLE
Galileo SSI index files have no SPACECRAFT_STOP_COUNT

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-data-projects#24]
As part of redoing the supplemental index files for Galileo SSI, SPACECRAFT_STOP_COUNT should be added. Then OPUS needs to be updated to include the new information.

See https://github.com/SETI/pds-opus/issues/318

**Comment by jnspitale** [comment]
Added SPACECRAFT_CLOCK_STOP_COUNT as well as SPACECRAFT_CLOCK_PRECISE_STOP_COUNT and SPACECRAFT_CLOCK_PRECISE_START_COUNT
