### ISSUE TITLE
Galileo SSI valid image rectangle

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-data-projects#25]
GOSSI images can have zero-filled columns on the four edges. A program needs to be written to examine each image, figure out the actual bounding box, and write the result to an index file. Once done, this information can be imported into OPUS to properly set the lesser/greater pixel size values.

See https://github.com/SETI/pds-opus/issues/317

**Comment by rfrenchseti** [comment]
Instead of analyzing the image, take a look at the TRUTH_WINDOW and CUT_OUT_WINDOW fields in the image labels.

**Comment by jnspitale** [comment]
CUT_OUT_WINDOW is already in the supplemental index.  Does that resolve this issue?

**Comment by rfrenchseti** [comment]
Yes, I think so.

**Comment by jnspitale** [comment]
Ok, closed.
