### ISSUE TITLE
Create a wrapper to run pds4_create_collection_member_index.py recursively

### ISSUE THREAD

**Issue by matthewtiscareno** [SETI/rms-data-projects#27]
The tool pds4_create_collection_member_index.py, as described in #21, works only on a single `collection_*.xml` file.  Once this is in working condition, create a wrapper to run it recursively on `collection_*.xml` files specified in an input file (such as the bundle_member_index produced by #20).

**Comment by matthewtiscareno** [comment]
I changed the name and description of this issue to clarify that we do not want to generalize pds4_create_collection_member_index.py itself (which was the previous wording), but rather create a wrapper that will run it recursively.

**Comment by esimpsons3ti** [comment]
Since the creation of this issue, the design plans for the indexing tool were changed. This functionality is now represented in the current iteration of the indexing tool, pds4_create_xml_index.py
