### ISSUE TITLE
Generalize pds4_create_data_index.py to accommodate arbitrary columns

### ISSUE THREAD

**Issue by matthewtiscareno** [SETI/rms-data-projects#28]
The tool pds4_create_data_index.py, as described in https://github.com/SETI/pds-data-projects/issues/22, produces an index file containing only on a single data column (namely `Target_Identification`). Once this is in working condition, generalize it to produce an index file containing columns as specified in an input file.

**Comment by esimpsons3ti** [comment]
This has been introduced in `pds4_create_xml_index.py` as a command-line argument called `--elements-file`, where user-specified elements can be scraped.
