### ISSUE TITLE
Create a wrapper to run pds4_create_data_index.py recursively

### ISSUE THREAD

**Issue by matthewtiscareno** [SETI/rms-data-projects#29]
The tool pds4_create_bundle_member_index.py, as described in https://github.com/SETI/pds-data-projects/issues/22, works only on a single `bundle_member_index.csv` file. Once this is in working condition, create a wrapper to run it recursively on `bundle_member_index.csv` files specified in an input file (such as the collection_member_index produced by #21).

Options should include 1) creating a `data_index.csv` alongside each `bundle_member_index.csv` file, or 2) putting all outputs (e.g., listing products for an entire "bundle set") into a single `cum_data_index.csv` in the working directory.

**Comment by matthewtiscareno** [comment]
I changed the name and description of this issue to clarify that we do not want to generalize pds4_create_data_index.py itself (which was the previous wording), but rather create a wrapper that will run it recursively.  Also, the description referenced an input issue (28) that is not actually relevant to this issue.

**Comment by esimpsons3ti** [comment]
Since the creation of this issue, the design plans for the indexing tool were changed. This functionality is now represented in the current iteration of the indexing tool, `pds4_create_xml_index.py`
