### ISSUE TITLE
Errors in PDS4 Cassini ISS bundles

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-data-projects#54]
The following fields appear to be incorrect in the XML labels for Cassini ISS images:

1)

```
    <cassini:telemetry_format_id>S&ER3</cassini:telemetry_format_id>
```

Note that `&` is not a valid character in XML files. It needs to be escaped as `S&amp;ER3`.

2)

```
    <cassini:image_mid_time>2017-146T21:28:05.816</cassini:image_mid_time>
```

This time is actually the stop time of the image, not the mid time.

**Comment by rfrenchseti** [comment]
Did we determine that point #1 was not actually true but was an issue with using a browser to view the XML files?

**Comment by matthewtiscareno** [comment]
I just spot-checked and, yes, I see the following:
`<cassini:telemetry_format_id>S&amp;ER3</cassini:telemetry_format_id>`

**Comment by matthewtiscareno** [comment]
As discussed in #122, somebody needs to fix the `cassini:image_mid_time` values so that we can proceed with publishing v2.0 of the Cassini ISS and VIMS bundles in PDS4.

**Comment by matthewtiscareno** [comment]
I've configured the Cassini ISS and VIMS v2.0 files in the `review-data` directory, so @esimpsons3ti can proceed with the `cassini:image_mid_time` correction.

**Comment by esimpsons3ti** [comment]
The attribute `cassini:image_mid_time` has been fixed.
