### ISSUE TITLE
Add geometry index for body-independent fields

### ISSUE THREAD

**Issue by jnspitale** [SETI/rms-data-projects#67]
RA and DEC are currenlty in the rings table, but it would make more sense to create a table describing the observation geometry independent of what is in the scene.  I.e., observation_summary.tab.

**Comment by rfrenchseti** [comment]
I agree. Good idea.

**Comment by rfrenchseti** [comment]
Is this finished?

**Comment by jnspitale** [comment]
This is addressed by the new sky_summary table.
