### ISSUE TITLE
Better deal with nil attributes

### ISSUE THREAD

**Issue by matthewtiscareno** [SETI/rms-data-projects#69]
When the tool finds an attribute that is set to "nil", it currently puts a value of "NaN" into the output table.  This does not inform the reader that the value is present but nil, nor does it relate the nilReason.  Furthermore, "NaN" is not an allowable value for ASCII tables in PDS4, and we would like these tables to be PDS4-compliant. 

We should discuss and then implement a more informative and PDS4-compliant way to fill the table in such cases.

**Comment by esimpsons3ti** [comment]
To add to this issue, there needs to be new default variables that are used in the event an attribute is `nil`. Values need to be determined not only each value type (integer, floating-point, dates, etc.) but also for each of the four `nilReason` values: inapplicable, anticipated, missing, and unknown.

**Comment by matthewtiscareno** [comment]
Examples:  
- For integers, the default special constants might be `-999`, `-998`, `-997`, and `-996` for the four possible `nilReason` values.
- For dates, they might be `0001-01-01T12:00`, `0002-01-01T12:00`, `0003-01-01T12:00`, and `0004-01-01T12:00`. 

Users should be able to redefine these special constants for each column, in case the default values are not clearly distinguishable from valid data.

**Comment by esimpsons3ti** [comment]
The data types I currently have are: Strings, Date and Time, and Numeric (`int` and `float`). Do I also need to account for Boolean values?

**Comment by esimpsons3ti** [comment]
Also what do people think of these values for strings and floats

```
Floats:
- -999.9, -999.8, -999.7, -999.6

Strings:
- “inapplicable”, “anticipated”, “unknown”, “missing”
```

**Comment by matthewtiscareno** [comment]
These all look great.  No, I don't think special constants would be present in a boolean column.

**Comment by matthewtiscareno** [comment]
These all look great. 

Why don't you set the code to crash if you have a boolean variable that is nil.  We'd have to figure out what to do in such a case, but I'm not sure whether it will ever come up.
