### ISSUE TITLE
Update comments for gridless geometric metadata columns

### ISSUE THREAD

**Issue by jnspitale** [SETI/rms-data-projects#73]
The comments need to be update for the gridless columns. For example,

  OBJECT                        = COLUMN
    COLUMN_NUMBER               = 39
    NAME                        = MINIMUM_CENTER_RESOLUTION
    DATA_TYPE                   = ASCII_REAL
    START_BYTE                  = 423
    BYTES                       = 10
    FORMAT                      = "F10.5"
    UNIT                        = "KM"
    NULL_CONSTANT               = -999.
    DESCRIPTION                 = "The linear size of a pixel as projected at
      the distance of the planet or specified target body.

      This value is defined by the instantaneous geometry at the time of the
      observation; it is independent of the field of view."
  END_OBJECT                    = COLUMN
If we're going to have this same label file for all instruments, we should have it say something like:

      This value is defined by the geometry during the time of the
      observation; it is independent of the field of view. This field
      tabulates the minimum value of the center resolution during
      the observation."

**Comment by rfrenchseti** [comment]
Is this finished?

**Comment by jnspitale** [comment]
This one is has not  yet been addressed.

**Comment by jnspitale** [comment]
See Sec. 3.1.3.3 in https://docs.google.com/document/d/1JVEhksHlru2jk8ZW6WPyZeGxReG0ccB-3GEQ2vyX4vg/edit
