### ISSUE TITLE
Finalize Europa Clipper EIS review (due 9/30)

### ISSUE THREAD

**Issue by matthewtiscareno** [SETI/rms-data-projects#92]
We previously provided a review of sample data products provided by the Europa Clipper EIS team.  Now an email has arrived from Paul Geissler of the Imaging Node saying the following:
> Hi All,
> 
> The EIS Team has provided a revised sample archive intended to resolve the concerns raised by our review. The revised sample archive can be found as "EIS_review_v2_eis_bundle_20240909" located in our EIS Prelaunch Review SharePoint site, here - [[URL redacted]]
> 
> The "Responses from Data Providers" folder of this SharePoint site has been updated with the EIS Team's responses to individual reviewers' comments (also attached to this message, for convenience).
> 
> Please check to see that these changes adequately address your concerns? And please feel free to make additional suggestions to improve the EIS archive, anytime before September 30.
> 
> Thanks, Paul

There probably is not much more to do.  Just glance at what they've provided and check whether they've addressed the issues we raised.  It might be worthwhile to also look at what other reviewers raised and what the responses were, as time allows.

**Comment by mace-space** [comment]
I've emailed my comments on the revised bundle to @matthewtiscareno @mseritan @mit3ch @esimpsons3ti
